name: Build and Deploy Dev Site to gen-alt-text-dev repository

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read # To checkout the current repo's dev branch

jobs:
  deploy-to-dev-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gen-alt-text 'dev' branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Deploy to gen-alt-text-dev repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT_FOR_DEV_REPO }}
          repository-name: symmetricalboy/gen-alt-text-dev # <-- IMPORTANT: REPLACE your-username
          branch: main # Target branch in gen-alt-text-dev
          folder: . # Deploy the root of the current repo's dev branch
          clean: true # Remove existing files in the target branch
          single-commit: true # Optional: creates a single commit in the target repo