name: Deploy Dev Site to gh-pages-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Required to push to the gh-pages-dev branch

jobs:
  build-and-deploy-dev:
    name: Build and Deploy Dev Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev # Ensure we are checking out the dev branch

      # --- ADD YOUR BUILD STEPS HERE (IF ANY) ---
      # If your site is just static HTML/CSS/JS and needs no build, you can skip this.
      # Example for a Node.js project (e.g., React, Vue, SvelteKit, Eleventy):
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20' # Specify your Node.js version
      #     cache: 'npm' # Or 'yarn' or 'pnpm'
      #
      # - name: Install dependencies
      #   run: npm ci # Or yarn install --frozen-lockfile or pnpm install --frozen-lockfile
      #
      # - name: Build project
      #   run: npm run build # Or your specific build script
      #   # Ensure your build output goes to a consistent directory, e.g., 'dist', 'build', 'public'
      #
      # --- END OF BUILD STEPS ---

      - name: Create CNAME file for dev site
        # If you have a build step, create CNAME in your build output directory.
        # Example: If build output is in 'dist/':
        # run: echo "alttextdev.symm.app" > dist/CNAME
        #
        # If no build step (serving files directly from dev branch root):
        run: echo "alttextdev.symm.app" > CNAME

      - name: Deploy to gh-pages-dev branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-dev # The branch to deploy the dev site to
          # Adjust publish_dir if you have a build step:
          # publish_dir: ./dist # Example for a build output directory named 'dist'
          # If no build step, and CNAME is created at root of checkout:
          publish_dir: .
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy dev site from ${{ github.sha }} to gh-pages-dev'
          # force_orphan: true # Optional: Creates a clean history for the publish_branch. Use with caution.
          # cname: alttextdev.symm.app # Can also be set here, but CNAME file in publish_dir is often preferred.