name: Deploy Main Site to Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Add CNAME file for production domain
      - name: Create CNAME file
        run: echo "alttext.symm.app" > CNAME
      
      # Deploy to gh-pages branch
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true 